#!/usr/bin/env bash

function main {
  set -exfu

  if [[ "$#" == 0 ]]; then
    if [[ -f write/config.ini ]]; then
      cd /usr/local/writefreely
      (set +f; ln -nfs /app/src/write/* .)
      exec ./writefreely
    else
      sleep 86400
    fi
  else
    exec "$@"
  fi
}

main "$@"
